# fly.toml app configuration file generated for db-server on 2023-05-19T13:35:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "db-server"
primary_region = "sin"

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
