# fly.toml app configuration file generated for endlib-backend on 2023-05-19T16:03:39+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "endlib-backend"
primary_region = "sin"

[http_service]
  internal_port = 1107
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
